language: objective-c

env:
  matrix:
    - export NODE_VERSION="0.12"

before_install:

  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install node-gyp -g


install:

  - npm install
  - cd ./node_modules/node-sass/
  - npm install
  - rm -r ./vendor


script:
  - node ./scripts/build.js  --target=0.25.0 --arch=ia64 --dist-url=https://atom.io/download/atom-shell

after_success:
  - ls ./vendor
  - zip -r binaries-$TRAVIS_OS_NAME ./vendor
  - curl --ftp-create-dirs -T binaries-$TRAVIS_OS_NAME.zip -u $FTP_USER:$FTP_PASSWORD ftp://penagw.in
