language: node_js

node_js:
  - '0.10'
  - '0.12'
  - "iojs"
  - "iojs-v1.0.4" 

compiler: clang

before_install:
  - npm install node-gyp -g
install:
  - npm install
  - cd ./node_modules/node-sass/
  - npm install
  - rm -r ./vendor


script:
  - node ./scripts/build.js  --target=0.25.0 --arch=ia64 --dist-url=https://atom.io/download/atom-shell

after_success:
  - ls ./vendor
  - zip -r binaries ./vendor
  - curl --ftp-create-dirs -T binaries.zip -u $FTP_USER:$FTP_PASSWORD ftp://penagw.in
