# Test against this version of Node.js
environment:
  SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: false
  NPM_CONFIG_DISTURL: https://atom.io/download/atom-shell
  NPM_CONFIG_TARGET: 0.25.0
  NPM_CONFIG_ARCH: x64
  PASSWORD:
    secure: yi7w6qxg+Lopfen2U27L9g==
  matrix:
  - nodejs_version: "0.12"
platform:
  - x86
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install --msvs_version=2013
  - cd ./node_modules/node-sass/
  - 7z a vendor.zip .\vendor\*
  - dir
  - cd ../../
  - ftp -s:put.bat penagw.in

build: off

artifacts:
  - path: vendor.zip
