# Test against this version of Node.js
environment:
  SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
  NPM_CONFIG_DISTURL: https://atom.io/download/atom-shell
  NPM_CONFIG_TARGET: 0.25.0
  NPM_CONFIG_ARCH: x64
  matrix:
  - nodejs_version: "0.12"
platform:
  - x86
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - cd ./node_modules/node-sass/

after_build:
  - jar -cMf binaries-windows.zip ./vendor 

artifacts:
  - path: binaries-windows.zip
